server.port=9999
spring.application.name=gestion-pressing

# Database Configuration
spring.datasource.url=jdbc:sqlite:pressing.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Mail Configuration (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sauleric34@gmail.com
spring.mail.password=hadwtlntdyeqrbgw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# i18n Configuration
spring.messages.basename=messages
spring.messages.encoding=UTF-8

# Error Handling
server.error.include-message=always
server.error.include-stacktrace=always
server.error.include-binding-errors=always

# Thymeleaf
spring.thymeleaf.cache=false

# JWT Configuration
pressing.app.jwtSecret=pressingManagementSecretKey2026AdvancedSecurityImplementationKeyKeyce
pressing.app.jwtExpirationMs=86400000
